# Generated by Django 5.2.16 on 2026-07-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name shown everywhere.', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Auto-filled from the name — leave blank.', max_length=120, unique=True)),
                ('category', models.CharField(choices=[('pre-made', 'Pre-made'), ('custom-sample', 'Custom work')], default='pre-made', max_length=20)),
                ('price_npr', models.PositiveIntegerField(help_text='Numbers only, e.g. 1500', verbose_name='Price (NPR)')),
                ('starting_from', models.BooleanField(default=False, help_text="Tick to show the price as 'Starting from NPR …' (for custom work).")),
                ('quantity', models.PositiveIntegerField(default=1, help_text="How many you have. At 0 the product shows as 'Sold out'.")),
                ('build_time', models.CharField(blank=True, help_text="How long it takes to build/deliver, e.g. '3 days'. Optional.", max_length=60)),
                ('short_description', models.CharField(help_text='One line shown on the product card.', max_length=160)),
                ('description', models.TextField(help_text='Full text shown on the product page.')),
                ('poly_count', models.CharField(blank=True, help_text='e.g. 12k tris', max_length=60)),
                ('formats', models.CharField(default='blend, fbx, obj', help_text='File formats, separated by commas.', max_length=100)),
                ('textures', models.CharField(blank=True, help_text='e.g. 2K PBR full set', max_length=100)),
                ('license_terms', models.CharField(blank=True, default='Personal & commercial use. No resale of the raw model files.', max_length=200)),
                ('featured', models.BooleanField(default=False, help_text='Tick to show this product on the Home page.')),
                ('published', models.BooleanField(default=True, help_text='Untick to hide this product from the site without deleting it.')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='PolyGhar', max_length=60)),
                ('tagline', models.CharField(default='3D models handcrafted in Blender', max_length=120)),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=80)),
                ('whatsapp_number', models.CharField(default='9779XXXXXXXXX', help_text='Digits only, starting with country code. Nepal example: 9779812345678 — no +, no spaces.', max_length=20)),
                ('custom_build_message', models.CharField(default="Hi! I'd like a custom 3D build. Here's what I need: ", help_text="Pre-filled WhatsApp text for the 'Request Custom Build' button.", max_length=300)),
                ('about_text', models.TextField(blank=True, default="I'm a 3D artist working entirely in Blender. Everything in the shop is modeled, textured and lit by me. Order over WhatsApp and you're talking directly to the person who built the model.", help_text='Your bio on the About page. Blank lines create new paragraphs.')),
                ('instagram_url', models.URLField(blank=True)),
                ('artstation_url', models.URLField(blank=True)),
                ('sketchfab_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='JPG or PNG. Around 1200×900 px looks best.', upload_to='products/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. The first image is the thumbnail.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
